/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Impaczus (https://sketchfab.com/Impaczus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hexagon-pyramid-cba5173173c04420b10dc04ac0135b8c
title: Hexagon Pyramid
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../pyramidScene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-11.19, -11.77, -0.2]}>
          <mesh material={materials['Material.003']} geometry={nodes.mesh_0.geometry} />
          <mesh material={materials['Material.004']} geometry={nodes.mesh_1.geometry} />
          <mesh material={materials.entrace_6} geometry={nodes.mesh_2.geometry} />
          <mesh material={materials.entrace_6_NONE} geometry={nodes.mesh_3.geometry} />
          <mesh material={materials.entrance_1} geometry={nodes.mesh_4.geometry} />
          <mesh material={materials.entrance_1_NONE} geometry={nodes.mesh_5.geometry} />
          <mesh material={materials.entrance_2} geometry={nodes.mesh_6.geometry} />
          <mesh material={materials.entrance_2_NONE} geometry={nodes.mesh_7.geometry} />
          <mesh material={materials.entrance_3} geometry={nodes.mesh_8.geometry} />
          <mesh material={materials.entrance_3_NONE} geometry={nodes.mesh_9.geometry} />
          <mesh material={materials.entrance_4} geometry={nodes.mesh_10.geometry} />
          <mesh material={materials.entrance_4_NONE} geometry={nodes.mesh_11.geometry} />
          <mesh material={materials.entrance_5} geometry={nodes.mesh_12.geometry} />
          <mesh material={materials.entrance_5_NONE} geometry={nodes.mesh_13.geometry} />
          <mesh material={materials.sand} geometry={nodes.mesh_14.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../pyramidScene.gltf')
